- plugins/org.wso2.developerstudio.eclipse.artifact.dataservice.validator/plugin.xml
Remove 'Data Services Validator Project' from Context Menu which opens up upon right clicking a data service project.
> Remove 'Data Services Validator Project' from Context Menu

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
> This PR is related to the disabling click outside of the bootstrap modal area to close modal in DSS editor
> Disable click outside of bootstrap modal area to close modal

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
When a transport protocol was deleted in the source view, changes are not reflected in the design view. The reason is that it only check for added transport protocols and does not clear removed ones.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/767
> Fixed: Issue 767

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
XMLSerializer in the IE adds prefix 'xmlns:NS#num="" NS#num:' when there is a colon (:) in an attribute name. Removed any such prefix.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/766
> Fixed: Issue 766

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
In Create\Edit Datasource wizard, When Database engine changes, automatically set the test connection's RDBMS version.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/778
> Fixed: Issue 788

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
Trying to configure the create datasource wizard before clearing the values. Hence configuration is done according to the values in previously created form. Changed the order so that form values are cleared before configuring the wizard.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/792
> Fixed: Issue 792

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
Deleting the authorization provider class name does not result in removing it. This is because when provider class is empty, previous element related to class is added again instead of removing.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/786
> Fixed: Issue 786

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
Change the URL format of the Apache Derby Database engine in the Create/Edit Datasource wizard.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/705
> Change URL format of Derby

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
When seting the checkbox value, only checks whether attribute 'returnUpdatedRowCount' exists or not. It should also check whether value of the returnUpdatedRowCount is true or false.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/791
> Fixed: Issue 791

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Add a password fields to the data source test connection section which will only be enable when the secret alias is enabled.
Related Issues: 
https://github.com/wso2/devstudio-tooling-ei/issues/798
https://github.com/wso2/devstudio-tooling-ei/issues/799
> Get password for test connection when secret alias enabled

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Avoid getting duplicate query entries at the query edit operation.
> Avoid duplicate query entries at edit

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
When Database engine changes, automatically set the test connection's RDBMS version.
Extending the solution in https://github.com/wso2/devstudio-tooling-dss/pull/157 to support for H2 database as well.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/778
> When H2 database selected, set test connection

- plugins/org.wso2.developerstudio.eclipse.ds.editor.xml/META-INF/MANIFEST.MF
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Includes following fixes,
1. Change name of the org.wso2.developerstudio.eclipse.ds.editor.xml
2. Fix of Issue 1010: Write <result> tag only if output mappings have any attributes or children.
3. Hide generate button and add-new button when output type is selected as "JSON".
4. Hide input and output mapping generation buttons when the data source is MongoDB.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1010
> Fix Issue: 1010

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Fix query fails to save. This is because saving invokes .includes function which does not support in windows browser environment.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1016
> Fix: Issue 1016

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Change default values to UPPERCASE to avoid errors when deploying.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1032
> [DSS] Change generated input mappings sqlType and paramType to UPPERCASE

- plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceProject/src/org/wso2/developerstudio/eclipse/artifact/dataserviceProject/ui/wizard/DataServiceProjectCreationWizard.java
- plugins/org.wso2.developerstudio.eclipse.artifact.datasourceproject/src/org/wso2/developerstudio/eclipse/artifact/datasourceProject/ui/wizard/DataSourceProjectCreationWizard.java
Set project nature of the following projects:
1. Data Source project
2. Data Service Project
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1046
> Fix: Pass project nature before project creation.

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
Issue: Trying to populate testConnectionDetails before setting the URL. 
Fix: Moving the populating code to the proper place.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1040
> Fix: Test connection details are not automatically populating

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
Toggle input groups when opening the wizard.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1075
> Fix: Edit output mapping wizard showing irrelevant fields

- plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
When trying to edit output mappings that do not have certain fields, edit output mapping wizard does not get populated. Hence, the values from the previously opened will be shown.
Fix: Allow to edit output mappings without certain fields by populating missing fields with empty strings.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/830
> Fix: Edit output mapping shows incorrect data

- plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceProject/plugin.xml
- plugins/org.wso2.developerstudio.eclipse.artifact.datasourceproject/plugin.xml
Rename project wizard extensions of data service and data source modules.
Fix https://github.com/wso2/devstudio-tooling-ei/issues/1212
> Rename project wizard extensions

- pom.xml
Reverts wso2/devstudio-tooling-dss#216
Moved eclipse migration-related commit to a new branch "eclipse-2020-migration"
> Revert "add changes to build pom file for eclipse 2020 migration"
