plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/plugin.xml
This is the initial enhancement related to [1]
[1] https://github.com/wso2/devstudio-tooling-ei/issues/31
=> Improve tooling dashboard

plugins/org.wso2.developerstudio.eclipse.artifact.datasource/plugin.xml
This adds the Datasource Poject and Data source artifact links to the dashboard
https://github.com/wso2/devstudio-tooling-ei/issues/68
=> Add Datasource project to dashboard

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/model/DataServiceModel.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/ui/wizard/NewDataSourceWizardPage.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/utils/DataServiceTemplateUtils.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/templates/Dataservice2.dbs, plugins/org.wso2.developerstudio.eclipse.ds.edit/plugin.properties, plugins/org.wso2.developerstudio.eclipse.ds.edit/src/org/wso2/developerstudio/eclipse/ds/provider/ConfigurationPropertyItemProvider.java, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/presentation/md/DetailSection.java, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/presentation/md/DetailSectionUiUtil.java, plugins/org.wso2.developerstudio.eclipse.ds/model/ds.ecore, plugins/org.wso2.developerstudio.eclipse.ds/model/ds.xsd, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/ConfigurationProperty.java, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/DsPackage.java, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/Query.java, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/impl/ConfigurationPropertyImpl.java, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/impl/DsPackageImpl.java, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/validation/ConfigurationPropertyValidator.java, plugins/org.wso2.developerstudio.eclipse.ds/src/org/wso2/developerstudio/eclipse/ds/validation/QueryValidator.java, plugins/org.wso2.developerstudio.eclipse.ds/text/description.txt
Introduce secret alias for RMDBS, cassandra and JNDI datasources in data service configuration.
Fix for https://github.com/wso2/devstudio-tooling-ei/issues/109
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Fixed https://github.com/wso2/devstudio-tooling-ei/issues/109

plugins/org.wso2.developerstudio.eclipse.ds/model/ds.genmodel
Add missing secretAlias attribute for the genmodel of DSS
> Link(s) to product documentation that addresses the changes of this …
=> Add secretAlias for genmodel

features/pom.xml, plugins/pom.xml
Add devsrelease profile to configure maven-jarsigner-plugin for update signing.
Fixed https://github.com/wso2/devstudio-tooling-ei/issues/123
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
=> Fix devstudio-tooling-ei#123

pom.xml
=> Update p2 URLs

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/TemplateProjectConstants.java
=> Edit Error Message

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/.classpath, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/.project
=> Commit .class and .project files

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/META-INF/MANIFEST.MF
=> Remove ESB dependencies

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/plugin.xml, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/ProjectCreationUtil.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/StudentDataServiceTemplate.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/TemplateProjectConstants.java
=> Open data service file on sample creation.

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/META-INF/MANIFEST.MF, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/ProjectCreationUtil.java
=> Open file in project explorer on sample creation

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/META-INF/MANIFEST.MF, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/Activator.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/util/TemplateProjectWizardModel.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/ArtifactTypeMapping.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/DSSArtifact.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/DSSProjectArtifact.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/DSSProjectCreationUtil.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/ProjectCreationUtil.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/StudentDataServiceTemplate.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/TemplateProjectWizardPage.java
=> Fix opening sample file on creation

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/ReadMe.html, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/dataservice/StudentDataService.dbs
=> Add readme html and modify dbs file

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/TemplateProjectConstants.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/TemplateProjectWizardPage.java
=> Disable default help in ceration wizard

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/ReadMe.html
update content for Student data service
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> update content for Student data service

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/ReadMe.html
=> Remove links in read me html

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/DSSProjectCreationUtil.java
Correct artifact type in artifact.xml.
Fixed https://github.com/wso2/product-ei/issues/2891
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the …
=> Fix product-ei#2891

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceProject/src/org/wso2/developerstudio/eclipse/artifact/dataserviceProject/ui/wizard/DataServiceProjectCreationWizard.java, plugins/org.wso2.developerstudio.eclipse.artifact.datasourceproject/src/org/wso2/developerstudio/eclipse/artifact/datasourceProject/ui/wizard/DataSourceProjectCreationWizard.java, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/presentation/DsModelWizard.java
Add JAVA EE perspective switching to data service project types
=> Fix data service/source project perspective switching

plugins/org.wso2.developerstudio.eclipse.artifact.datasource/plugin.xml, plugins/org.wso2.developerstudio.eclipse.artifact.datasourceproject/src/org/wso2/developerstudio/eclipse/artifact/datasourceProject/ui/wizard/DataSourceProjectCreationWizard.java
Fix data source project context menu items and project creation issues
=> Fix data source project nature

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/META-INF/MANIFEST.MF
This PR is to export org.wso2.developerstudio.eclipse.artifact.dataservice.artifact package
This is related to https://github.com/wso2/devstudio-tooling-esb/pull/962
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Export dataservice artifact package

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/StudentDataServiceTemplate.java
Switch perspective to J2EE after creating the student data service sample.
> Link(s) to product documentation that addresses …
=> Switch perspective after dss sample creation

plugins/org.wso2.developerstudio.eclipse.ds.edit/src/org/wso2/developerstudio/eclipse/ds/provider/ElementMappingItemProvider.java
Enabling requiredRoles attribute in DSS query result elements.
=> Enable requiredRoles attr in DSS query result elements

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/servlets/DSSEditorServlet.java
Implementing data service operations' related functionality.
=> Data service operations' related functionality

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Add edit functionality for data service operations.
=> Add edit functionality for operations

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Add resources section functionality for DSS editor
=> Add Resources for DSS editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Minor refactorings in DSS editor.
=> Minor refactorings in DSS editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Add UI elements for output mapping
=> Add UI elements for output mapping

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/servlets/DSSEditorServlet.java
Refactoring DSS editor webapp.
=> Refactor DSS editor webapp

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Query output mapping implementation
=> Query output mapping implementation

plugins/org.wso2.developerstudio.eclipse.ds.editor.xml/plugin.xml, plugins/org.wso2.developerstudio.eclipse.ds.editor/build.properties, plugins/org.wso2.developerstudio.eclipse.ds.editor/plugin.xml, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/common.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/config.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/event-trigger.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/operation.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/query.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/resource.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/editors/DSSMultiPageEditor.java
Add data service source editor validation using xsd schema files, and add support for content assist for data service.
=> Add data service source validation and content assist support

plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/config.xsd, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
Update data service schema to support oData attribute and multiple configs.
=> Update data service schema

plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/editors/DSSMultiPageEditor.java
Disable validation on save event on the DSSEditor.
=> Disable validation on save event.

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/ui/wizard/NewDataSourceWizardPage.java, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Implement advanced properties of data services in the dss web editor.
=> Implement advanced properties of data services

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
Saving advanced properties to the dataservice configuration.
=> Saving advanced properties

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
Fixes https://github.com/wso2/devstudio-tooling-ei/issues/704
=> Fix https://github.com/wso2/devstudio-tooling-ei/issues/704

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fixes https://github.com/wso2/devstudio-tooling-ei/issues/710
=> Fix https://github.com/wso2/devstudio-tooling-ei/issues/710

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/dataservice/StudentDataService.dbs, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/XmlBeautify.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Enable query output mapping and add query advanced functionality for dss editor.
Fix https://github.com/wso2/devstudio-tooling-ei/issues/706
=> Enable query output mapping and add query advanced functionality

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
Fix https://github.com/wso2/devstudio-tooling-ei/issues/709
=> Fix devstudio-tooling-ei#709

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
Fixing https://github.com/wso2/devstudio-tooling-ei/issues/703
=> Fix https://github.com/wso2/devstudio-tooling-ei/issues/703

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/styles.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fixing https://github.com/wso2/devstudio-tooling-ei/issues/714
=> Fix https://github.com/wso2/devstudio-tooling-ei/issues/714

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Adding secret alias support for DSS editor
=> Add secret alias support for DSS editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
Implement transport properties
=> Implement transport properties

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/editors/DSSMultiPageEditor.java
Correct updating order of query elements.
=> Correct update order of queries

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
Allow edit query output mapping.
=> Allow edit query output mapping

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/templates/Dataservice1.dbs, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/templates/Dataservice2.dbs, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/presentation/custom/perspective/DataServiceEditorPerspective.java
Remove data source creation wizard in data service creation wizard.
=> Remove data source creation wizard

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
Enable streaming support for data service resource.
=> Enable streaming support for resource

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
Correct populating data service description.
=> Correct populating dataservice description

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js
Remove unwanted data service operation functions.
=> Remove unwanted operation functions

plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/editors/DSSMultiPageEditor.java
Disable switching to design view when the source view content fails the data service validation.
=> Disable switching to design view when source content falis validation

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
Fix configuring query output mapping.
=> Fix configuring query output mapping

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/RESTDataService/ReadMe.html, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/RESTDataService/dataservice/RESTDataService.dbs, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/plugin.xml, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/src/org/wso2/developerstudio/eclipse/artifact/dataserviceTemplate/wizard/RESTDataServiceTemplate.java
> Resolves wso2/devstudio-tooling-ei#722
=> Add sample for a REST dataservice

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/RESTDataService/dataservice/RESTDataService.dbs, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/dataservice/StudentDataService.dbs
Update descriptions of data service samples.
=> Update descriptions of data service samples

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Add query outupt mapping generation for 'select *' queries.
=> Add output mapping generation

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/domutils.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Refactor javascript files to compatible with IE 9.
=> Refactor data handler for IE 9

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
> update javascript commands in dss editor
=> update javascript commands in dss editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/domutils.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
=> Update beautify for IE 9

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/domutils.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js
=> Disable prettify for IE

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
> Update input fields CSS in DSS editor.
=> Update input fields css in dss editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Replace form submit functions with button click events.
=> Bind save events for buttons

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Fixing validator issues in DSS editor
=> Fix validator issues in DSS editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/domutils.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Fix value populating issues with IE
=> Fix value populating issues with IE

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
> Enabled form validation onsubmit for forms
=> Enabled form validation onsubmit for forms

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Remove empty rows in query input mapping validator table.
=> Remove empty rows in validator table

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Reverts wso2/devstudio-tooling-dss#128
=> Revert "Enabled form validation onsubmit for forms"

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
Add validation for form submit.
=> Add validation for form submit

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
> Add form validations for the dss editor
=> Add form validations for the dss editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
=> Fixed: issue 757

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Rename DataSource ID to DataSource Name
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/756
=> Rename Datasource ID

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/table-functions.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
DSS editor usability improvements.
=> DSS editor usability improvements

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
Fix query output mapping generation on Windows.
=> Fix output mapping generation on Windows

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
> Remove notification modal to notifications label in form onSubmit errors
=> Remove notification modal to notifications label in form onSubmit errors 

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
When data source URL is changes automatically change test connection host, port and database name.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/705
=> Auto fill test connection

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
=> Fixed: issue 770

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
=> Fixed: issue 775

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js
=> Fixed: issue 760

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceProject/src/org/wso2/developerstudio/eclipse/artifact/dataserviceProject/ui/wizard/DataServiceProjectCreationWizard.java
Open project pom and link the editor on dss project creation.
=> Open project pom on dss project creation

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fix https://github.com/wso2/devstudio-tooling-ei/issues/764
=> Fix devstudio-ei#764

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fix https://github.com/wso2/devstudio-tooling-ei/issues/772
=> Fix devstudio-ei#772

plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/editors/DSSMultiPageEditor.java
Fix https://github.com/wso2/devstudio-tooling-ei/issues/768
=> Fix devstudio-ei#768

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/domutils.js
Fix https://github.com/wso2/devstudio-tooling-ei/issues/758
=> Fix devstudio-ei#758

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceTemplate/Samples/StudentDataService/dataservice/StudentDataService.dbs, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/servlets/DSSEditorServlet.java
Remove unused attributes form StudentDataService sample.
=> Remove unused attributes form the sample

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js
=> Fixed: issue 771

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/META-INF/MANIFEST.MF, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/plugin.xml, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/validators/DataServiceResourceTester.java
=> Fixed: issue 320

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fix https://github.com/wso2/devstudio-tooling-ei/issues/782
=> Fix devstudio-ei#782

plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java, plugins/org.wso2.developerstudio.eclipse.artifact.dataservice/src/org/wso2/developerstudio/eclipse/artifact/dataservice/validators/DataServiceFieldController.java
=> Fixed: issue 780

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/advanced-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Enable support for serviceStatus attribute of the data service.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/795
=> Adding Support for service status

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/ds-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fix wso2/devstudio-tooling-ei#328
=> Fix devstudio-ei#328

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/table-functions.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
=> Fixed: issue 785

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
=> Fixed: issue 801

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/ds-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fix https://github.com/wso2/devstudio-tooling-ei/issues/802
=> Fix devstudio-ei#802

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/domutils.js
Fix https://github.com/wso2/devstudio-tooling-ei/issues/758
=> Fix devstuio-ei#758

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
=> Fixed: issue 812

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js
Check whether query or operation parameter is empty before saving the operation.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/815
=> Fixed: Issue 815

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
>Fix: https://github.com/wso2/devstudio-tooling-ei/issues/814
=> Add confirmation for deleting operations parameters

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Fix https://github.com/wso2/devstudio-tooling-ei/issues/817
=> Fix devstudio-ei#817

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js
Check whether values is valid (Numeric) when the key is pressed.
Related Issues: https://github.com/wso2/devstudio-tooling-ei/issues/813
=> Fixed Issue: 813

plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceProject/META-INF/MANIFEST.MF, plugins/org.wso2.developerstudio.eclipse.artifact.dataserviceProject/src/org/wso2/developerstudio/eclipse/artifact/dataserviceProject/ui/wizard/DataServiceProjectCreationWizard.java
Link with the current editor at data service project creation.
=> Link with edior at project creation

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
=> Fixed: issue 823

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/datasources-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/operation-validation.js
Fix https://github.com/wso2/devstudio-tooling-ei/issues/816 for Windows.
=> Fix devstudio-ei#816

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Change the title of the add/edit query form when editing the query.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/831
=> Fixed: Issue 831

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
> Fix: https://github.com/wso2/devstudio-tooling-ei/issues/912
=> Update the Write concern values for MongoDB data sources

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
>Fix: https://github.com/wso2/devstudio-tooling-ei/issues/904
=> Change SQL Query to Expression for  MongoDB datasources

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/data-handler.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
Add a new attribute `publishSwagger` to the dataservice config.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/893
=> Fix: Issue 893

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/color-theme.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/input.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/modal.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/styles.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
=> Add style changes

plugins/org.wso2.developerstudio.eclipse.artifact.datasourceproject/plugin.xml
=> Add datasource project in MMM context menu

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js
Generate input mappings for SQL queries.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/975
=> Generate input mappings for SQL queries

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
Allow to remove attributes(element, rowName, defaultNamespace, xsltPath) from result element.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1013
=> Fix: Issue 1013

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/input.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/styles.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
=> Refactor DSS editor styles

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/constants.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/js/query-util.js, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html, plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
1. Adding `optional` to schema file.
2. Adding support to edit using UI.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1021
=> Add optional attribute to query input parameter

plugins/org.wso2.developerstudio.eclipse.ds.editor/resources/schema/dss_schema.xsd
Add param-name to the scheme.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1074
=> Add param-name to scheme

plugins/org.wso2.developerstudio.eclipse.ds.editor/src/org/wso2/developerstudio/eclipse/ds/editors/DSSMultiPageEditor.java
=> Fix file stream not closed issue in data service editor

plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/color-theme.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/input.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/openSans.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/assets/css/styles.css, plugins/org.wso2.developerstudio.eclipse.ds.editor/DSSEditor/index.html
Incorporating DSS editor theme changes.
=> Incorporating DSS editor theme changes

features/org.wso2.developerstudio.eclipse.data.service.feature/feature.xml
Remove dss sample template feature.
=> Remove dss template feature

pom.xml
=> add changes to build pom file for eclipse 2020 migration

plugins/org.wso2.developerstudio.eclipse.ds.editor/plugin.xml, plugins/org.wso2.developerstudio.eclipse.ds.editor/src/DSSMultipageEditorActionBarContributer.java
=> fix issue with undo/redo not working in eclipse 2020

README.md
=> Update README.md added deprecated note
